"""
EVA Content Engine — Voice DNA Loader
Loosely coupled. No user data baked in.

Loads voice profile from (in priority order):
  1. ~/.eva/user_profile.json         — generated by EVA Onboarding Workflow
  2. EVA_USER_PROFILE env var          — path override for white-label installs
  3. Built-in defaults                 — generic fallback only

WHITE-LABEL USAGE:
  Each installation ships its own user_profile.json.
  Content Engine, Morning Brief, Outreach Sequences all read from this file.
  Voice DNA, banned words, examples, business context — all user-defined.
  No personal data hardcoded here.

TO CONFIGURE:
  Run `eva setup` (coming: modules/onboarding) or place user_profile.json in ~/.eva/
  See: schema at modules/onboarding/user_profile.schema.json
"""

import json
import os
from pathlib import Path


# ── Default fallback profile (generic, no personal data) ─────────────────────
_DEFAULT_PROFILE = {
    "user": {
        "name": "the founder",
        "role": "entrepreneur",
        "location": "",
        "company": "",
        "north_star": "",
        "philosophy": "",
    },
    "voice": {
        "style": "Short sentences. One idea per line. Quiet confidence over hype.",
        "banned_words": [
            "game-changer", "revolutionary", "excited to announce", "thrilled",
            "leverage", "synergy", "ecosystem", "empower", "journey", "passionate",
            "cutting-edge", "unlock", "thought leadership", "paradigm",
            "transformative", "innovative", "seamless", "robust", "learnings",
            "deep dive", "circle back", "move the needle", "bandwidth",
        ],
        "examples": [],
        "hashtags": {
            "always_include": [],
            "max_count": 7,
        },
    },
    "business": {
        "product": "",
        "offer": "",
        "target_audience": "",
        "waitlist_url": "",
    },
}


def load_profile() -> dict:
    """
    Load user_profile.json from ~/.eva/ or ENV override.
    Falls back to default generic profile if not found.
    Each EVA installation ships its own profile — never hardcoded.
    """
    env_path = os.getenv("EVA_USER_PROFILE")
    candidates = [
        Path(env_path) if env_path else None,
        Path.home() / ".eva" / "user_profile.json",
        Path(__file__).parent / "user_profile.json",  # local dev override
    ]

    for path in candidates:
        if path and path.exists():
            try:
                with open(path) as f:
                    profile = json.load(f)
                print(f"[voice_dna] Loaded profile from {path}")
                return profile
            except Exception as e:
                print(f"[voice_dna] Failed to load {path}: {e}")

    print("[voice_dna] No user_profile.json found — using default generic voice")
    return _DEFAULT_PROFILE


def build_system_prompt(profile: dict) -> str:
    """Build the LLM system prompt dynamically from the loaded user profile."""
    u = profile.get("user", {})
    v = profile.get("voice", {})
    b = profile.get("business", {})

    name       = u.get("name", "the founder")
    role       = u.get("role", "entrepreneur")
    company    = u.get("company", "")
    north_star = u.get("north_star", "")
    philosophy = u.get("philosophy", "")
    style      = v.get("style", "Short sentences. Quiet confidence.")
    banned     = ", ".join(v.get("banned_words", []))
    product    = b.get("product", "")
    audience   = b.get("target_audience", "")
    waitlist   = b.get("waitlist_url", "")

    examples_str = ""
    for ex in v.get("examples", []):
        examples_str += f"\n\nContext: {ex.get('context','')}\nPost:\n{ex.get('post','')}\n---"

    prompt = f"""You are EVA's Content Engine writing LinkedIn posts on behalf of {name}.

VOICE STYLE:
{style}

NEVER USE THESE WORDS: {banned}

POST STRUCTURE:
1. Hook — one line. Contrast or confession. Not a question.
2. Gap — 2-4 lines. Set up the tension.
3. Turn — one quiet insight.
4. Proof — what they actually built or did.
5. Close — quiet invitation. Never a hard sell.
"""

    if name and role:
        prompt += f"\nABOUT THE AUTHOR: {name} is a {role}"
        if company: prompt += f" at {company}"
        prompt += "."
    if north_star: prompt += f"\nNORTH STAR: {north_star}"
    if philosophy: prompt += f"\nPHILOSOPHY: {philosophy}"
    if product:    prompt += f"\nPRODUCT: {product}"
    if audience:   prompt += f"\nTARGET AUDIENCE: {audience}"
    if waitlist:   prompt += f"\nWAITLIST URL: {waitlist}"
    if examples_str: prompt += f"\n\nVOICE EXAMPLES TO MATCH:{examples_str}"

    prompt += "\n\nWrite only the post. No explanations. No meta-commentary."
    return prompt


# ── Module-level: load once on import ────────────────────────────────────────
_profile          = load_profile()
VOICE_SYSTEM_PROMPT = build_system_prompt(_profile)
VOICE_EXAMPLES    = _profile.get("voice", {}).get("examples", [])


def check_banned_words(text: str) -> list[str]:
    """Return banned words found in text (sourced from loaded profile)."""
    banned = _profile.get("voice", {}).get("banned_words", [])
    text_lower = text.lower()
    return [w for w in banned if w in text_lower]
