"""
EVA Deal Scout — Pydantic models (v5)
Module 3 of the EVA digital acquisition intelligence system.
"""

from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field


VALID_STAGES = ["tracking", "in_progress", "nda_signed", "loi_sent", "due_diligence", "closed"]
VALID_BUY_VS_BUILD = ["buy", "build", "hybrid"]
VALID_MARKET_STATUS = ["available", "sold", "off_market"]


class Deal(BaseModel):
    id: str                          # UUID
    source: str                      # "flippa" | "empire_flippers" | "acquire" | "manual"
    listing_id: str
    url: str
    name: str
    category: str                    # "SaaS" | "Content" | "Services" | "Education" | "Digital Products"
    monthly_net: float               # monthly net profit ($)
    annual_multiple: float           # normalized annual multiple (EF: divide raw by 12)
    asking_price: float
    age_years: float
    notes: str = ""

    # Stage pipeline (replaces old status field)
    stage: str = "tracking"          # "tracking" | "in_progress" | "nda_signed" | "loi_sent" | "due_diligence" | "closed"

    # Archive flags
    is_archived: bool = False
    archive_reason: str = ""
    archived_at: str = ""            # ISO timestamp

    # Buy vs Build fields
    buy_vs_build_decision: str = "buy"   # "buy" | "build" | "hybrid"
    buy_vs_build_reason: str = ""        # free-text explanation

    # Availability
    market_status: str = "available"     # "available" | "sold" | "off_market"
    listing_price_original: float = 0    # original asking price at time of discovery

    # Scoring dimensions (0–100 each; overall 0–10)
    cashflow_score: float = 0.0
    moat_score: float = 0.0              # difficulty to replicate / defensibility depth
    ai_proof_score: float = 0.0          # runway before AI disruption
    value_add_score: float = 0.0         # upside buyer can add
    buy_vs_build_score: float = 0.0      # 0–10, rescaled to 0–100 in composite
    risk_score: float = 0.0              # multi-factor risk exposure (0–100, higher = more risk)
    mitigation_score: float = 0.0       # how well identified risks can be offset (0–100, higher = better)
    competitor_analysis_score: float = 0.0  # market crowding & competitive intensity (0–100)
    company_life_score: float = 0.0      # estimated survival runway if untouched (0–100)
    overall_score: float = 0.0           # weighted composite 0–10

    # Company life estimate (derived)
    company_life_months: float = 0.0     # estimated months of runway if owner does nothing
    company_life_label: str = ""         # human label: "Terminal", "Declining", "Stable", "Growing / Durable"

    # Risk breakdown (derived) — individual risk flags surfaced by analyzer
    risk_flags: list = []               # list of identified risk strings
    mitigation_actions: list = []       # list of concrete mitigation action strings

    # Score rationales — one brief sentence per dimension, auto-generated by analyzer
    score_rationales: dict = {}          # keys match score field names, values are brief strings

    # Financial analysis
    down_payment: float = 0.0              # 20% of asking_price
    seller_finance_amount: float = 0.0     # 80% of asking_price
    monthly_debt_service: float = 0.0      # PMT at 7% / 60 months
    net_monthly_cashflow: float = 0.0      # monthly_net - debt_service
    heloc_used: float = 0.0                # == down_payment (funded via HELOC @ 9.5%)
    heloc_interest_monthly: float = 0.0    # heloc_used * 0.095 / 12
    net_after_heloc: float = 0.0           # net_monthly_cashflow - heloc_interest_monthly

    # Timestamps
    discovered_at: str = ""           # when first added
    stage_changed_at: str = ""        # last stage transition timestamp
    closed_at: str = ""               # when closed
    created_at: str = ""
    updated_at: str = ""


class DealCreate(BaseModel):
    """Payload accepted by POST /deals (all score/financial fields are optional overrides)."""
    source: str = "manual"
    listing_id: str = ""
    url: str = ""
    name: str
    category: str = "SaaS"
    monthly_net: float
    annual_multiple: float
    asking_price: float
    age_years: float
    notes: str = ""

    # Stage pipeline
    stage: str = "tracking"

    # Buy vs Build
    buy_vs_build_decision: str = "buy"
    buy_vs_build_reason: str = ""

    # Availability
    market_status: str = "available"
    listing_price_original: float = 0

    # Optional manual overrides for scoring dimensions
    cashflow_score: Optional[float] = None
    moat_score: Optional[float] = None
    ai_proof_score: Optional[float] = None
    value_add_score: Optional[float] = None
    buy_vs_build_score: Optional[float] = None
    risk_score: Optional[float] = None
    mitigation_score: Optional[float] = None
    competitor_analysis_score: Optional[float] = None
    company_life_score: Optional[float] = None
    overall_score: Optional[float] = None


class DealUpdate(BaseModel):
    """Payload accepted by PUT /deals/{id} — all fields optional."""
    source: Optional[str] = None
    listing_id: Optional[str] = None
    url: Optional[str] = None
    name: Optional[str] = None
    category: Optional[str] = None
    monthly_net: Optional[float] = None
    annual_multiple: Optional[float] = None
    asking_price: Optional[float] = None
    age_years: Optional[float] = None
    notes: Optional[str] = None

    # Stage pipeline
    stage: Optional[str] = None

    # Buy vs Build
    buy_vs_build_decision: Optional[str] = None
    buy_vs_build_reason: Optional[str] = None

    # Availability
    market_status: Optional[str] = None
    listing_price_original: Optional[float] = None

    # Scores
    cashflow_score: Optional[float] = None
    moat_score: Optional[float] = None
    ai_proof_score: Optional[float] = None
    value_add_score: Optional[float] = None
    buy_vs_build_score: Optional[float] = None
    risk_score: Optional[float] = None
    mitigation_score: Optional[float] = None
    competitor_analysis_score: Optional[float] = None
    company_life_score: Optional[float] = None
    overall_score: Optional[float] = None


class StageUpdate(BaseModel):
    """Payload for POST /deals/{id}/stage."""
    stage: str
    reason: str = ""
    note: str = ""


class ArchiveRequest(BaseModel):
    """Payload for POST /deals/{id}/archive."""
    reason: str = ""
    note: str = ""


class DealHistory(BaseModel):
    """A single deal history event record."""
    id: str
    deal_id: str
    event_type: str   # "stage_change" | "archive" | "unarchive" | "field_update" | "score_update" | "created"
    from_value: str = ""
    to_value: str = ""
    field_name: str = ""
    reason: str = ""
    note: str = ""
    created_at: str


class HealthResponse(BaseModel):
    status: str
    module: str
    version: str
    db: str
